### ISSUE TITLE
Rename plugin

### ISSUE THREAD

**Issue by jo-mueller** [jo-mueller/napari-stl-exporter#24]
Since this plugin now supports not only exporting but also importing surface data formats, it could be renamed to something like `napari-surface-io`

@haesleinhuepf do you have an opinion on this? Do you know how to change the name of a napari plugin? Is this even possible (let alone advisable ^^")?

**Comment by haesleinhuepf** [comment]
Hi Johannes,

you can decommission a plugin like I did in this commit:
https://github.com/haesleinhuepf/napari-mahotas-image-processing/commit/d6c19a27b1e5acb994aa1e698692394e73f783a3#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52L14

Afterwards, you can rename it and then deploy the new thing to pypi.

Btw. I'm curious, do you know of any other plugins that allow reading/writing STL files?

**Comment by jo-mueller** [comment]
> Btw. I'm curious, do you know of any other plugins that allow reading/writing STL files?

I guess you are hinting at pymeshlab, which wasn't around at the time the stl-exporter was first released. Given the circumstances I'd rather eventually decommission the stl-exporter eventually.
