### ISSUE TITLE
Mixing spaces and tabs

### ISSUE THREAD

**Issue by goanpeca** [jo-mueller/napari-stl-exporter#33]
Hi @jo-mueller, looking into https://github.com/conda-forge/napari-stl-exporter-feedstock/pull/4 and updating the patch it seems that tabs and spaces are mixed in the file. Just letting you know so you can fix in a future release.

<img width="477" alt="Screen Shot 2022-09-05 at 8 20 45 PM" src="https://user-images.githubusercontent.com/3627835/188527682-4338041f-f676-47ee-bb90-3785e72819cc.png">

PS: I have an extension on the browser called "Refined GitHub" which adds some nice stuff, like seeing tabs and spaces on github files.

Cheers!

**Comment by jo-mueller** [comment]
Hi @goanpeca thanks a bunch for spotting this and also for the tip with the browser extension, it's very helpful :) I think this was introduced here PR #32 , I wasn't aware that inconsistent tabs in the config files would lead to trouble during the azure build process - I probably made this mistake in some other repos as well!

**Comment by goanpeca** [comment]
> I wasn't aware that inconsistent tabs in the config files would lead to trouble during the azure build process - I probably made this mistake in some other repos as well!

In general it should not be an issue, but it just makes the creation of the patch files a bit more convoluted :)

It is just nice to be consistent ;-)
