### ISSUE TITLE
Pyramid example data is just black

### ISSUE THREAD

**Issue by haesleinhuepf** [jo-mueller/napari-stl-exporter#6]
Hi Johannes @jo-mueller ,

the pyramid example data appears black in napari. 

![image](https://user-images.githubusercontent.com/12660498/139803670-ce611426-60f1-4028-831a-2065fdf4347d.png)

Any ideas why?

Best,
Robert

**Comment by jo-mueller** [comment]
That's strange... is it the image from the main branch?

![screenshot](https://user-images.githubusercontent.com/38459088/139822124-68671938-dd19-40a3-9554-1c5c6f6e3c2f.jpg)

Maybe it's the contrast limits? It seems like napari also assumes default contrast limits of (0 - 255), but the pyramid is only (0, 1).

**Comment by haesleinhuepf** [comment]
Ok, I just tried again and it works now. Not sure, what I did yesterday. I'm going to close this.

Thanks for the headsup!
